name: Test Windows SDK
permissions:
  contents: read
    
on:
  push:
    branch:
      - main
      - branch

jobs:
  sdk-install:
    runs-on: windows-latest

    steps:
      # - name: Set up Windows SDK
      #   uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
      #   with:
      #     sdk-version: 26100

      - name: List SDK Directory
        run: |
          dir "C:\Program Files (x86)\Windows Kits\10\bin"
          dir "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64"
